import flet as ft

# Overlay
OVERLAY_MOUNT_FRAME_DELAY_S = 0.016

# Toast
TOAST_TRANSITION_MS = 300
TOAST_TRANSITION_CURVE = ft.AnimationCurve.DECELERATE
TOAST_CLOSE_DELAY_S = TOAST_TRANSITION_MS / 1000
TOAST_UPDATE_MS = 140
TOAST_UPDATE_DELAY_S = TOAST_UPDATE_MS / 1000
TOAST_UPDATE_DIM_OPACITY = 0.56
TOAST_HIDDEN_OPACITY = 0.0
TOAST_VISIBLE_OPACITY = 1.0
TOAST_HIDDEN_OFFSET = ft.Offset(0, -1)
TOAST_VISIBLE_OFFSET = ft.Offset(0, 0)

# Sheet
SHEET_TRANSITION_MS = 280
SHEET_TRANSITION_CURVE = ft.AnimationCurve.FAST_OUT_SLOWIN
SHEET_CLOSE_DELAY_S = SHEET_TRANSITION_MS / 1000
SHEET_ANCHOR_CLOSED_OFFSET = ft.Offset(0, 1.04)
SHEET_ANCHOR_OPEN_OFFSET = ft.Offset(0, 0)
SHEET_SURFACE_CLOSED_OFFSET = ft.Offset(0, 0.045)
SHEET_SURFACE_OPEN_OFFSET = ft.Offset(0, 0)
SHEET_SURFACE_CLOSED_SCALE = 0.94
SHEET_SURFACE_OPEN_SCALE = 1.0
SHEET_SURFACE_CLOSED_OPACITY = 0.0
SHEET_SURFACE_OPEN_OPACITY = 1.0

# Route
ROUTE_FADE_MS = 300
ROUTE_FADE_CURVE = ft.AnimationCurve.EASE_IN_OUT

# Auth
AUTH_SHAKE_MS = 40
AUTH_SHAKE_CURVE = ft.AnimationCurve.LINEAR

# Controls
ICON_BUTTON_STYLE_MS = 180

# App
APP_SWITCHER_DURATION_MS = 300
APP_SWITCHER_REVERSE_DURATION_MS = 0

# Tooltip
TOOLTIP_WAIT_DURATION_MS = 200
TOOLTIP_SHOW_DURATION_MS = 4000


def make(duration_ms: int, curve: ft.AnimationCurve) -> ft.Animation:
    return ft.Animation(duration_ms, curve)
